# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-09 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MomoTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runoob_title', models.CharField(max_length=20)),
                ('runoob_author', models.CharField(max_length=20)),
                ('submission_date', models.CharField(max_length=20)),
                ('runoob_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'momo_test',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RunoobTbl',
            fields=[
                ('runoob_id', models.AutoField(primary_key=True, serialize=False)),
                ('runoob_title', models.CharField(max_length=100)),
                ('runoob_author', models.CharField(max_length=40)),
                ('submission_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'runoob_tbl',
                'managed': False,
            },
        ),
    ]
