# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('momo', '0003_result_urls'),
    ]

    operations = [
        migrations.CreateModel(
            name='crawl_urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'crawl_urls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='file_urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'file_urls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='lfi_urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=500)),
                ('payload', models.CharField(max_length=1000)),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'lfi_urls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='sql_urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('dbms', models.CharField(max_length=100)),
                ('dbms_version', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=10000)),
            ],
            options={
                'db_table': 'sql_urls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='xss_urls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('payload', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'xss_urls',
                'managed': False,
            },
        ),
    ]
